wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683935467.726412
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.10.0
      5: 0.15.2
      8:
      - 5
num_layers:
  desc: null
  value: 5
deform_layers:
  desc: null
  value:
  - false
  - false
  - false
  - true
  - true
